---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript
    exclude_paths:
     - "app/assets/javascripts/defer/*"
     - "app/assets/javascripts/ember-addons/*"
     - "lib/autospec/*"
     - "lib/es6_module_transpiler/*"
     - "lib/highlight_js/*"
     - "lib/import/*"
     - "lib/javascripts/*"
     - "lib/tasks/*"
     - "lib/*.js"
     - "public/*"
     - "script/*"
     - "spec/*"
     - "test/*"
     - "vendor/*"
  eslint:
    enabled: true
    channel: eslint-3
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
