sources:
  bundler: true

allowed:
  - 0bsd
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - cc0-1.0
  - isc
  - mit
  - ruby

ignored:
  bundler:
    - abbrev # Ruby (default gem)
    - base64 # Ruby (default gem)
    - bigdecimal # Ruby (default gem)
    - cgi # Ruby (default gem)
    - date # Ruby (default gem)
    - digest # Ruby (default gem)
    - erb # Ruby (default gem)
    - io-console # Ruby (default gem)
    - io-wait # Ruby (default gem)
    - irb # Ruby (default gem)
    - json # Ruby (default gem)
    - logger # Ruby (default gem)
    - mutex_m # BSD-2-Clause
    - net-http # Ruby (default gem)
    - net-protocol # Ruby (default gem)
    - openssl # Ruby (default gem)
    - ostruct # Ruby (default gem)
    - pp # Ruby (default gem)
    - prettyprint # Ruby (default gem)
    - racc # Ruby (default gem)
    - rchardet # LGPL
    - rdoc # Ruby (default gem)
    - reline # Ruby (default gem)
    - ruby2_keywords # Ruby (default gem)
    - stringio # Ruby (default gem)
    - strscan # Ruby (default gem)
    - timeout # Ruby (default gem)
    - tsort # Ruby (default gem)
    - uri # Ruby (default gem)

reviewed:
  bundler:
    - activerecord # MIT
    - benchmark # Ruby
    - coderay # MIT
    - concurrent-ruby # MIT
    - css_parser # MIT
    - drb # BSD-2-Clause
    - dry-initializer # MIT
    - excon # MIT
    - faraday-em_http # MIT
    - faraday-em_synchrony # MIT
    - faraday-excon # MIT
    - faraday-httpclient # MIT
    - faraday-net_http # MIT
    - faraday-patron # MIT
    - faraday-rack # MIT
    - hashery # BSD-2-Clause
    - highline # Ruby or GPL-2.0
    - htmlentities # MIT
    - image_size # MIT
    - jwt # MIT
    - kgio # LGPL-2.1+
    - logstash-event # Apache-2.0
    - net-imap # Ruby (bundled gem)
    - net-pop # Ruby (bundled gem)
    - net-smtp # Ruby (bundled gem)
    - nio4r # MIT + BSD
    - omniauth # MIT
    - pg # Ruby
    - pitchfork # Ruby or GPLv2/GPLv3
    - r2 # Apache-2.0 (Twitter)
    - raindrops # LGPL-2.1+
    - rubyzip # Ruby
    - securerandom # Ruby
    - sidekiq # LGPL (Sidekiq)
    - tilt # MIT
    - ttfunk # Ruby or GPLv2/GPLv3
    - unf # BSD-2-Clause
    - unicorn # Ruby or GPLv2/GPLv3
