inherit_gem:
  rubocop-discourse: stree-compat.yml

inherit_mode:
  merge:
    - Exclude

# Still work to do in ensuring we don't link old files
Discourse/NoAddReferenceOrAliasesActiveRecordMigration:
  Enabled: false

Discourse/NoResetColumnInformationInMigrations:
  Enabled: true

Discourse/Plugins/CallRequiresPlugin:
  Include:
    - "plugins/*/app/controllers/**/*"

Discourse/Plugins/UsePluginInstanceOn:
  Include:
    - "plugins/**/*"

Discourse/Plugins/NamespaceMethods:
  Include:
    - "plugins/**/*"

Discourse/Plugins/NamespaceConstants:
  Include:
    - "plugins/**/*"

Discourse/Plugins/UseRequireRelative:
  Include:
    - "plugins/**/*"

Discourse/Plugins/NoMonkeyPatching:
  Include:
    - "plugins/**/*"

Lint/Debugger:
  Exclude:
    - script/**/*
  DebuggerMethods:
    SystemHelpers:
      - pause_test

RSpec/EmptyLineAfterExample:
  Enabled: true

RSpec/EmptyLineAfterExampleGroup:
  Enabled: true

RSpec/EmptyLineAfterFinalLet:
  Enabled: true

RSpec/EmptyLineAfterHook:
  Enabled: true

RSpec/ExampleWording:
  Enabled: true
  DisallowedExamples:
    - works
    - succeeds
    - fails
    - does something
    - behaves correctly
    - handles it
    - handles errors
    - returns the expected result

RSpec/HookArgument:
  Enabled: true
  EnforcedStyle: implicit

RSpec/HooksBeforeExamples:
  Enabled: true

RSpec/InstanceVariable:
  Enabled: true
  AssignmentOnly: true

RSpec/LetBeforeExamples:
  Enabled: true

RSpec/LetSetup:
  Enabled: true

RSpec/MultipleDescribes:
  Enabled: true

RSpec/NestedGroups:
  Enabled: true
  Max: 4

RSpec/RepeatedDescription:
  Enabled: true

RSpec/RepeatedExample:
  Enabled: true

RSpec/RepeatedExampleGroupBody:
  Enabled: true

RSpec/RepeatedExampleGroupDescription:
  Enabled: true

RSpec/ScatteredSetup:
  Enabled: true

Style/RedundantFreeze:
  Enabled: true

Style/RedundantConditional:
  Enabled: true

Lint/DuplicateMagicComment:
  Enabled: true

Lint/IdentityComparison:
  Enabled: true

Lint/SymbolConversion:
  Enabled: true

Style/RedundantParentheses:
  Enabled: true

Style/RedundantBegin:
  Enabled: true

Rails/FilePath:
  Enabled: true

Style/RedundantSelf:
  Enabled: true
