inherit_gem:
  rubocop-discourse: stree-compat.yml

# Still work to do in ensuring we don't link old files
Discourse/NoAddReferenceOrAliasesActiveRecordMigration:
  Enabled: false

Discourse/NoResetColumnInformationInMigrations:
  Enabled: true

Discourse/Plugins/CallRequiresPlugin:
  Include:
    - "plugins/*/app/controllers/**/*"

Discourse/Plugins/UsePluginInstanceOn:
  Include:
    - "plugins/**/*"

Discourse/Plugins/NamespaceMethods:
  Include:
    - "plugins/**/*"

Discourse/Plugins/NamespaceConstants:
  Include:
    - "plugins/**/*"

Discourse/Plugins/UseRequireRelative:
  Include:
    - "plugins/**/*"

Discourse/Plugins/NoMonkeyPatching:
  Include:
    - "plugins/**/*"

Lint/Debugger:
  Exclude:
    - script/**/*
  DebuggerMethods:
    SystemHelpers:
      - pause_test

RSpec/InstanceVariable:
  Enabled: true
  Include:
    - spec/models/**/*
