AllCops:
  # Include gemspec and Rakefile
  Includes:
    - '**/*.gemspec'
    - '**/Rakefile'
  Excludes: []

# Prefer ' strings when you don't need string interpolation or special symbols.
StringLiterals:
  Enabled: false

LineLength:
  Enabled: true
  Max: 180

# Avoid methods longer than 10 lines of code
MethodLength:
  Enabled: true
  CountComments: false  # count full line comments?
  Max: 10

# Document classes and non-namespace modules.
Documentation:
  Enabled: false

CaseEquality:
  Enabled: false

ClassVars:
  Enabled: false
