strictPeerDependencies: true
strictDepBuilds: true
onlyBuiltDependencies:
- lefthook
ignoredBuiltDependencies:
- "@zoom/meetingsdk"
- core-js
- rete
packages:
- "docs/developer-guides"
- "frontend/deprecation-silencer"
- "frontend/discourse"
- "frontend/discourse-i18n"
- "frontend/discourse-markdown-it"
- "frontend/pretty-text"
- "frontend/pretty-text-processor"
- "frontend/asset-processor"
- "frontend/discourse-types"
- "plugins/automation"
- "plugins/chat"
- "plugins/checklist"
- "plugins/discourse-adplugin"
- "plugins/discourse-affiliate"
- "plugins/discourse-ai"
- "plugins/discourse-apple-auth"
- "plugins/discourse-assign"
- "plugins/discourse-cakeday"
- "plugins/discourse-calendar"
- "plugins/discourse-chat-integration"
- "plugins/discourse-data-explorer"
- "plugins/discourse-details"
- "plugins/discourse-gamification"
- "plugins/discourse-github"
- "plugins/discourse-graphviz"
- "plugins/discourse-captcha"
- "plugins/discourse-lazy-videos"
- "plugins/discourse-local-dates"
- "plugins/discourse-login-with-amazon"
- "plugins/discourse-lti"
- "plugins/discourse-math"
- "plugins/discourse-microsoft-auth"
- "plugins/discourse-narrative-bot"
- "plugins/discourse-oauth2-basic"
- "plugins/discourse-openid-connect"
- "plugins/discourse-patreon"
- "plugins/discourse-policy"
- "plugins/discourse-post-voting"
- "plugins/discourse-presence"
- "plugins/discourse-reactions"
- "plugins/discourse-rss-polling"
- "plugins/discourse-solved"
- "plugins/discourse-subscriptions"
- "plugins/discourse-templates"
- "plugins/discourse-topic-voting"
- "plugins/discourse-user-notes"
- "plugins/discourse-zendesk-plugin"
- "plugins/footnote"
- "plugins/poll"
- "plugins/spoiler-alert"
- "plugins/styleguide"
- "themes/horizon"
patchedDependencies:
  "ember-this-fallback@0.4.0": "patches/ember-this-fallback@0.4.0.patch"
  "babel-plugin-debug-macros@0.3.4": "patches/babel-plugin-debug-macros@0.3.4.patch"
  "licensee@11.1.1": "patches/licensee@11.1.1.patch"
  "@ember-compat/tracked-built-ins@0.9.1": "patches/@ember-compat__tracked-built-ins@0.9.1.patch"
  "ember-source@6.10.1": "patches/ember-source@6.10.1.patch"
  "http-proxy@1.18.1": "patches/http-proxy@1.18.1.patch"
  "ember-exam@10.1.0": "patches/ember-exam@10.1.0.patch"
  "message-bus-client": "patches/message-bus-client.patch"
  "ember-buffered-proxy": "patches/ember-buffered-proxy.patch"
  "pikaday": "patches/pikaday.patch"
peerDependencyRules:
  allowedVersions:
    "@mixer/parallel-prettier>prettier": "*"
    "ember-this-fallback>ember-source": "*"
    "ember-this-fallback>ember-cli-htmlbars": "*"
    "@fullcalendar/moment-timezone>moment-timezone": "*"
  ignoreMissing:
    - "webpack"
    - "@types/react"
overrides:
  "@ember/test-waiters": "4.1.1"
  "babel-plugin-ember-template-compilation@~2.3.0": "2.4.1"
  "broccoli-babel-transpiler@8.0.0": "^8.0.2"
allowedDeprecatedVersions:
  "@babel/plugin-proposal-class-properties": "*"
  "@babel/plugin-proposal-private-methods": "*"
  "@babel/plugin-proposal-private-property-in-object": "*"
  "@babel/polyfill": "*"
  "@types/glob": "*"
  "are-we-there-yet": "*"
  "consolidate": "*"
  "core-js": "*"
  "gauge": "*"
  "glob": "*"
  "inflight": "*"
  "lodash.omit": "*"
  "node-domexception": "*"
  "npmlog": "*"
  "raw-body": "*"
  "resolve-url": "*"
  "rimraf": "*"
  "sane": "*"
  "source-map-resolve": "*"
  "source-map-url": "*"
  "sourcemap-codec": "*"
  "urix": "*"
  "whatwg-encoding": "*"
