packages:
- "frontend/custom-proxy"
- "frontend/deprecation-silencer"
- "frontend/discourse"
- "frontend/discourse-i18n"
- "frontend/discourse-markdown-it"
- "frontend/discourse-plugins"
- "frontend/discourse-widget-hbs"
- "frontend/ember-cli-progress-ci"
- "frontend/pretty-text"
- "frontend/asset-processor"
