strictPeerDependencies: true
packages:
- "frontend/custom-proxy"
- "frontend/deprecation-silencer"
- "frontend/discourse"
- "frontend/discourse-i18n"
- "frontend/discourse-markdown-it"
- "frontend/discourse-plugins"
- "frontend/ember-cli-progress-ci"
- "frontend/pretty-text"
- "frontend/asset-processor"
- "frontend/discourse-types"
- "plugins/automation"
- "plugins/chat"
- "plugins/checklist"
- "plugins/discourse-adplugin"
- "plugins/discourse-affiliate"
- "plugins/discourse-ai"
- "plugins/discourse-apple-auth"
- "plugins/discourse-assign"
- "plugins/discourse-cakeday"
- "plugins/discourse-calendar"
- "plugins/discourse-chat-integration"
- "plugins/discourse-data-explorer"
- "plugins/discourse-details"
- "plugins/discourse-gamification"
- "plugins/discourse-github"
- "plugins/discourse-graphviz"
- "plugins/discourse-hcaptcha"
- "plugins/discourse-lazy-videos"
- "plugins/discourse-local-dates"
- "plugins/discourse-login-with-amazon"
- "plugins/discourse-lti"
- "plugins/discourse-math"
- "plugins/discourse-microsoft-auth"
- "plugins/discourse-narrative-bot"
- "plugins/discourse-oauth2-basic"
- "plugins/discourse-openid-connect"
- "plugins/discourse-patreon"
- "plugins/discourse-policy"
- "plugins/discourse-post-voting"
- "plugins/discourse-presence"
- "plugins/discourse-reactions"
- "plugins/discourse-rss-polling"
- "plugins/discourse-solved"
- "plugins/discourse-subscriptions"
- "plugins/discourse-templates"
- "plugins/discourse-topic-voting"
- "plugins/discourse-user-notes"
- "plugins/discourse-zendesk-plugin"
- "plugins/footnote"
- "plugins/poll"
- "plugins/spoiler-alert"
- "plugins/styleguide"
allowedDeprecatedVersions:
  "@babel/plugin-proposal-class-properties": "*"
  "@babel/plugin-proposal-private-methods": "*"
  "@babel/plugin-proposal-private-property-in-object": "*"
  "@babel/polyfill": "*"
  "@types/glob": "*"
  "are-we-there-yet": "*"
  "consolidate": "*"
  "core-js": "*"
  "gauge": "*"
  "glob": "*"
  "inflight": "*"
  "lodash.omit": "*"
  "node-domexception": "*"
  "npmlog": "*"
  "raw-body": "*"
  "resolve-url": "*"
  "rimraf": "*"
  "sane": "*"
  "source-map-resolve": "*"
  "source-map-url": "*"
  "sourcemap-codec": "*"
  "urix": "*"
  "whatwg-encoding": "*"
