packages:
- "frontend/custom-proxy"
- "frontend/deprecation-silencer"
- "frontend/dialog-holder"
- "frontend/discourse"
- "frontend/discourse-i18n"
- "frontend/discourse-markdown-it"
- "frontend/discourse-plugins"
- "frontend/discourse-widget-hbs"
- "frontend/ember-cli-progress-ci"
- "frontend/float-kit"
- "frontend/pretty-text"
- "frontend/select-kit"
- "frontend/asset-processor"
- "frontend/truth-helpers"
