# frozen_string_literal: true

source "https://rubygems.org"

# the minimal Ruby version required by migration-tooling
ruby ">= 3.2.2"

# `activesupport` gem needs to be in sync with the Rails version of Discourse, see `/Gemfile`
lock_file = %w[Gemfile.lock ../Gemfile.lock].detect { File.exist?(_1) }
activesupport_version =
  Bundler::LockfileParser
    .new(Bundler.read_file(lock_file))
    .specs
    .detect { _1.name == "activesupport" }
    .version
gem "activesupport", "= #{activesupport_version}", require: "active_support"

# for SQLite
gem "extralite-bundle", "~> 2.8", require: "extralite", github: "digital-fabric/extralite"
gem "lru_redux", "~> 1.1", require: false

# for communication between process forks
gem "msgpack", "~> 1.7"

# for CLI
gem "colored2", "~> 4.0"
gem "thor", "~> 1.3"

# auto-loading
gem "zeitwerk", "~> 2.6"
