# frozen_string_literal: true

source "https://rubygems.org"

# the minimal Ruby version required by migration-tooling
ruby "~> 3.2.2"

# `activesupport` gem needs to be in sync with the Rails version of Discourse, see `/Gemfile`
gem "activesupport", "< 7.1", require: "active_support"

# for SQLite
gem "extralite-bundle", "~> 2.8", require: "extralite"
gem "lru_redux", "~> 1.1", require: false

# for communication between process forks
gem "msgpack", "~> 1.7"

# for CLI
gem "colored2", "~> 4.0"
gem "thor", "~> 1.3"

# auto-loading
gem "zeitwerk", "~> 2.6"
