# frozen_string_literal: true

source "https://rubygems.org"

ruby "~> 3.2.2"

gem "activesupport", "~> 7.1"
gem "extralite-bundle", "~> 2.8"
gem "msgpack", "~> 1.7"
gem "thor", "~> 1.3"
gem "zeitwerk", "~> 2.6"
