<ComboBox
  @valueProperty="value"
  @content={{this.groupOptions}}
  @value={{this.groupId}}
  @onChange={{this.onChange}}
  @options={{hash
    allowAny=this.filter.allow_any
    autoInsertNoneItem=this.filter.auto_insert_none_item
    filterable=true
    none="admin.dashboard.reports.groups"
  }}
/>