inherit_from: ../.rubocop.yml

Style/HashSyntax:
  EnforcedShorthandSyntax: always

Style/ModuleFunction:
  EnforcedStyle: forbidden

Style/EndlessMethod:
  EnforcedStyle: disallow

Style/Send:
  Enabled: true
