module Highlighter

   @@language_map = {
      "Apache" =>                "apache.js",
      "Bash" =>                  "bash.js",
      "C#" =>                    "cs.js",
      "C++" =>                   "cpp.js",
      "CSS" =>                   "css.js",
      "CoffeeScript" =>          "coffeescript.js",
      "Diff" =>                  "diff.js",
      "HTML, XML" =>             "xml.js",
      "HTTP" =>                  "http.js",
      "Ini" =>                   "ini.js",
      "JSON" =>                  "json.js",
      "Java" =>                  "java.js",
      "JavaScript" =>            "javascript.js",
      "Makefile" =>              "makefile.js",
      "Markdown" =>              "markdown.js",
      "Nginx" =>                 "nginx.js",
      "Objective C" =>           "objectivec.js",
      "PHP" =>                   "php.js",
      "Perl" =>                  "perl.js",
      "Python" =>                "python.js",
      "Ruby" =>                  "ruby.js",
      "SQL" =>                   "sql.js",
      "1C" =>                    "1c.js",
      "AVR Assembler" =>         "avrasm.js",
      "ActionScript" =>          "actionscript.js",
      "AppleScript" =>           "applescript.js",
      "AsciiDoc" =>              "asciidoc.js",
      "AutoHotkey" =>            "autohotkey.js",
      "Axapta" =>                "axapta.js",
      "Brainfuck" =>             "brainfuck.js",
      "CMake" =>                 "cmake.js",
      "Cap’n Proto" =>           "capnproto.js",
      "Clojure" =>               "clojure.js",
      "D" =>                     "d.js",
      "DOS .bat" =>              "dos.js",
      "Dart" =>                  "dart.js",
      "Delphi" =>                "delphi.js",
      "Django" =>                "django.js",
      "Dust" =>                  "dust.js",
      "ERB (Embedded Ruby)" =>   "erb.js",
      "Elixir" =>                "elixir.js",
      "Erlang" =>                "erlang.js",
      "Erlang REPL" =>           "erlang-rep.js",
      "F#" =>                    "fsharp.js",
      "FIX" =>                   "fix.js",
      "G-code (ISO 6983)" =>     "gcode.js",
      "GLSL" =>                  "glsl.js",
      "Gherkin" =>               "gherkin.js",
      "Go" =>                    "go.js",
      "Gradle" =>                "gradle.js",
      "Groovy" =>                "groovy.js",
      "Haml" =>                  "haml.js",
      "Handlebars" =>            "handlebars.js",
      "Haskell" =>               "haskell.js",
      "Haxe" =>                  "haxe.js",
      "Intel x86 Assembly" =>    "x86asm.js",
      "Lasso" =>                 "lasso.js",
      "Less" =>                  "less.js",
      "Lisp" =>                  "lisp.js",
      "LiveCode" =>              "livecodeserver.js",
      "LiveScript" =>            "livescript.js",
      "Lua" =>                   "lua.js",
      "MEL" =>                   "mel.js",
      "Mathematica" =>           "mathematica.js",
      "Matlab" =>                "matlab.js",
      "Mizar" =>                 "mizar.js",
      "Monkey" =>                "monkey.js",
      "NSIS" =>                  "nsis.js",
      "Nimrod" =>                "nimrod.js",
      "Nix" =>                   "nix.js",
      "OCaml" =>                 "ocaml.js",
      "Oracle Rules Language" => "ruleslanguage.js",
      "Oxygene" =>               "oxygene.js",
      "Parser3" =>               "parser3.js",
      "PowerShell" =>            "powershell.js",
      "Processing" =>            "processing.js",
      "Protocol Buffers" =>      "protobuf.js",
      "Puppet" =>                "puppet.js",
      "Python profile" =>        "profile.js",
      "Q" =>                     "q.js",
      "R" =>                     "r.js",
      "RenderMan RIB" =>         "rib.js",
      "RenderMan RSL" =>         "rsl.js",
      "Rust" =>                  "rust.js",
      "SCSS" =>                  "scss.js",
      "Scala" =>                 "scala.js",
      "Scheme" =>                "scheme.js",
      "Scilab" =>                "scilab.js",
      "Smalltalk" =>             "smalltalk.js",
      "Stylus" =>                "stylus.js",
      "Swift" =>                 "swift.js",
      "Tcl" =>                   "tcl.js",
      "TeX" =>                   "tex.js",
      "Thrift" =>                "thrift.js",
      "Twig" =>                  "twig.js",
      "TypeScript" =>            "typescript.js",
      "VB.NET" =>                "vbnet.js",
      "VBScript" =>              "vbscript.js",
      "VBScript in HTML" =>      "vbscript-html.js",
      "VHDL" =>                  "vhdl.js",
      "Vala" =>                  "vala.js",
      "Vim Script" =>            "vim.js",
      "XL" =>                    "xl.js"
   }

   def self.generate(languages, path)
      files = languages.map{|name| @@language_map[name.strip]}

      result = [] << File.read("#{path}/highlight.js")
      files.each{ |f| result << File.read("#{path}/languages/#{f}")}

      result.join("\n")
   end
end
