import { isEmpty } from "@ember/utils";
import { userPath } from "discourse/lib/url";

const _additionalAttributes = [];

export function includeAttributes(...attributes) {
  attributes.forEach(a => _additionalAttributes.push(a));
}

export function transformBasicPost(post) {
  // Note: it can be dangerous to not use `get` in Ember code, but this is significantly
  // faster and has tests to confirm it works. We only call `get` when the property is a CP
  const postAttrs = {
    id: post.id,
    hidden: post.hidden,
    deleted: post.get("deleted"),
    deleted_at: post.deleted_at,
    user_deleted: post.user_deleted,
    isDeleted: post.deleted_at || post.user_deleted, // xxxxx
    deletedByAvatarTemplate: null,
    deletedByUsername: null,
    primary_group_name: post.primary_group_name,
    primary_group_flair_url: post.primary_group_flair_url,
    primary_group_flair_bg_color: post.primary_group_flair_bg_color,
    primary_group_flair_color: post.primary_group_flair_color,
    wiki: post.wiki,
    lastWikiEdit: post.last_wiki_edit,
    firstPost: post.post_number === 1,
    post_number: post.post_number,
    cooked: post.cooked,
    via_email: post.via_email,
    isAutoGenerated: post.is_auto_generated,
    user_id: post.user_id,
    usernameUrl: userPath(post.username),
    username: post.username,
    avatar_template: post.avatar_template,
    bookmarked: post.bookmarked,
    bookmarkedWithReminder: post.bookmarked_with_reminder,
    bookmarkReminderAt: post.bookmark_reminder_at,
    yours: post.yours,
    shareUrl: post.get("shareUrl"),
    staff: post.staff,
    admin: post.admin,
    moderator: post.moderator,
    new_user: post.trust_level === 0,
    name: post.name,
    user_title: post.user_title,
    created_at: post.created_at,
    updated_at: post.updated_at,
    canDelete: post.can_delete,
    showFlagDelete: false,
    canRecover: post.can_recover,
    canEdit: post.can_edit,
    canFlag: !isEmpty(post.get("flagsAvailable")),
    canReviewTopic: false,
    reviewableId: post.reviewable_id,
    reviewableScoreCount: post.reviewable_score_count,
    reviewableScorePendingCount: post.reviewable_score_pending_count,
    version: post.version,
    canRecoverTopic: false,
    canDeleteTopic: false,
    canViewEditHistory: post.can_view_edit_history,
    canWiki: post.can_wiki,
    showLike: false,
    liked: false,
    canToggleLike: false,
    likeCount: false,
    actionsSummary: null,
    read: post.read,
    replyToUsername: null,
    replyToAvatarTemplate: null,
    reply_to_post_number: post.reply_to_post_number,
    cooked_hidden: !!post.cooked_hidden,
    expandablePost: false,
    replyCount: post.reply_count,
    locked: post.locked,
    userCustomFields: post.user_custom_fields,
    readCount: post.readers_count
  };

  _additionalAttributes.forEach(a => (postAttrs[a] = post[a]));

  return postAttrs;
}

export default function transformPost(
  currentUser,
  site,
  post,
  prevPost,
  nextPost
) {
  // Note: it can be dangerous to not use `get` in Ember code, but this is significantly
  // faster and has tests to confirm it works. We only call `get` when the property is a CP
  const postType = post.post_type;
  const postTypes = site.post_types;
  const topic = post.topic;
  const details = topic.get("details");

  const postAttrs = transformBasicPost(post);

  const createdBy = details.created_by || {};

  postAttrs.topicId = topic.id;
  postAttrs.topicOwner = createdBy.id === post.user_id;
  postAttrs.topicCreatedById = createdBy.id;
  postAttrs.post_type = postType;
  postAttrs.via_email = post.via_email;
  postAttrs.isAutoGenerated = post.is_auto_generated;
  postAttrs.isModeratorAction = postType === postTypes.moderator_action;
  postAttrs.isWhisper = postType === postTypes.whisper;
  postAttrs.isSmallAction =
    postType === postTypes.small_action || post.action_code === "split_topic";
  postAttrs.canBookmark = !!currentUser;
  postAttrs.canManage = currentUser && currentUser.get("canManageTopic");
  postAttrs.canViewRawEmail =
    currentUser && (currentUser.id === post.user_id || currentUser.staff);
  postAttrs.canReplyAsNewTopic = details.can_reply_as_new_topic;
  postAttrs.canReviewTopic = !!details.can_review_topic;
  postAttrs.isWarning = topic.is_warning;
  postAttrs.links = post.get("internalLinks");
  postAttrs.replyDirectlyBelow =
    nextPost && nextPost.reply_to_post_number === post.post_number;
  postAttrs.replyDirectlyAbove =
    prevPost && post.reply_to_post_number === prevPost.post_number;
  postAttrs.linkCounts = post.link_counts;
  postAttrs.actionCode = post.action_code;
  postAttrs.actionCodeWho = post.action_code_who;
  postAttrs.topicUrl = topic.get("url");
  postAttrs.isSaving = post.isSaving;

  if (post.notice_type) {
    postAttrs.noticeType = post.notice_type;
    if (postAttrs.noticeType === "custom") {
      postAttrs.noticeMessage = post.notice_args;
    } else if (postAttrs.noticeType === "returning_user") {
      postAttrs.noticeTime = new Date(post.notice_args);
    }
  }

  const showPMMap =
    topic.archetype === "private_message" && post.post_number === 1;
  if (showPMMap) {
    postAttrs.showPMMap = true;
    postAttrs.allowedGroups = details.allowed_groups;
    postAttrs.allowedUsers = details.allowed_users;
    postAttrs.canRemoveAllowedUsers = details.can_remove_allowed_users;
    postAttrs.canRemoveSelfId = details.can_remove_self_id;
    postAttrs.canInvite = details.can_invite_to;
  }

  const showTopicMap =
    showPMMap ||
    (post.post_number === 1 &&
      topic.archetype === "regular" &&
      topic.posts_count > 1);
  if (showTopicMap) {
    postAttrs.showTopicMap = true;
    postAttrs.topicCreatedAt = topic.created_at;
    postAttrs.createdByUsername = createdBy.username;
    postAttrs.createdByAvatarTemplate = createdBy.avatar_template;
    postAttrs.createdByName = createdBy.name;

    postAttrs.lastPostUrl = topic.get("lastPostUrl");
    postAttrs.lastPostUsername = details.last_poster.username;
    postAttrs.lastPostAvatarTemplate = details.last_poster.avatar_template;
    postAttrs.lastPostName = details.last_poster.name;
    postAttrs.lastPostAt = topic.last_posted_at;

    postAttrs.topicReplyCount = topic.get("replyCount");
    postAttrs.topicViews = topic.views;
    postAttrs.topicViewsHeat = topic.get("viewsHeat");

    postAttrs.participantCount = topic.participant_count;
    postAttrs.topicLikeCount = topic.like_count;
    postAttrs.topicLinks = details.links;
    if (postAttrs.topicLinks) {
      postAttrs.topicLinkLength = details.links.length;
    }
    postAttrs.topicPostsCount = topic.posts_count;

    postAttrs.participants = details.participants;

    const postStream = topic.get("postStream");
    postAttrs.userFilters = postStream.userFilters;
    postAttrs.topicSummaryEnabled = postStream.summary;
    postAttrs.topicWordCount = topic.word_count;
    postAttrs.hasTopicSummary = topic.has_summary;
  }

  if (postAttrs.isDeleted) {
    postAttrs.deletedByAvatarTemplate = post.get(
      "postDeletedBy.avatar_template"
    );
    postAttrs.deletedByUsername = post.get("postDeletedBy.username");
  }

  const replyToUser = post.get("reply_to_user");
  if (replyToUser) {
    postAttrs.replyToUsername = replyToUser.username;
    postAttrs.replyToAvatarTemplate = replyToUser.avatar_template;
  }

  if (post.actions_summary) {
    postAttrs.actionsSummary = post.actions_summary
      .filter(a => {
        return a.actionType.name_key !== "like" && a.acted;
      })
      .map(a => {
        const action = a.actionType.name_key;

        return {
          id: a.id,
          postId: post.id,
          action,
          canUndo: a.can_undo,
          description: I18n.t(`post.actions.by_you.${action}`)
        };
      });
  }

  const likeAction = post.likeAction;
  if (likeAction) {
    postAttrs.liked = likeAction.acted;
    postAttrs.canToggleLike = likeAction.get("canToggle");
    postAttrs.showLike = postAttrs.liked || postAttrs.canToggleLike;
    postAttrs.likeCount = likeAction.count;
  }

  if (!currentUser) {
    postAttrs.showLike = !topic.archived;
  }

  if (postAttrs.post_number === 1) {
    postAttrs.canRecoverTopic = postAttrs.isDeleted && details.can_recover;
    postAttrs.canDeleteTopic = !postAttrs.isDeleted && details.can_delete;
    postAttrs.expandablePost = topic.expandable_first_post;

    // Show a "Flag to delete" message if not staff and you can't
    // otherwise delete it.
    postAttrs.showFlagDelete =
      !postAttrs.canDelete &&
      postAttrs.yours &&
      currentUser &&
      !currentUser.staff;
  } else {
    postAttrs.canRecover = postAttrs.isDeleted && postAttrs.canRecover;
    postAttrs.canDelete =
      postAttrs.canDelete &&
      !post.deleted_at &&
      currentUser &&
      (currentUser.staff || !post.user_deleted);
  }

  _additionalAttributes.forEach(a => (postAttrs[a] = post[a]));

  return postAttrs;
}
