# frozen_string_literal: true

require "email/receiver"

RSpec.describe Email::Receiver, "#process!" do
  before do
    SiteSetting.email_in = true
    SiteSetting.enable_staged_users = true
  end

  def configure_reply_by_email
    SiteSetting.reply_by_email_address = "reply+%{reply_key}@bar.com"
    SiteSetting.manual_polling_enabled = true
    SiteSetting.reply_by_email_enabled = true
  end

  def process(email_name, opts = {})
    Email::Receiver.new(email(email_name), opts).process!
  end

  shared_examples "creates topic with forwarded message as quote" do |destination, address|
    it "creates topic with forwarded message as quote" do
      expect { process(:forwarded_email_1) }.to change(Topic, :count)

      topic = Topic.last
      if destination == :category
        expect(topic.category).to eq(Category.where(email_in: address).first)
      else
        expect(topic.archetype).to eq(Archetype.private_message)
        expect(topic.allowed_groups).to eq(Group.where(incoming_email: address))
      end

      post = Post.last

      expect(post.user.email).to eq("ba@bar.com")
      expect(post.raw).to eq(<<~RAW.chomp)
        @team, can you have a look at this email below?

        [quote]
        From: Some One &lt;some@one\\.com&gt;
        To: Ba Bar &lt;ba@bar\\.com&gt;
        Date: Mon, 1 Dec 2016 00:13:37 \\+0100
        Subject: Discoursing much?

        Hello Ba Bar,

        Discoursing much today?

        XoXo
        [/quote]
      RAW
    end
  end

  shared_examples "does not create staged users" do |email_name, expected_exception|
    it "does not create staged users" do
      staged_user_count = User.where(staged: true).count
      User.expects(:create).never
      User.expects(:create!).never

      if expected_exception
        expect { process(email_name) }.to raise_error(expected_exception)
      else
        process(email_name)
      end

      expect(User.where(staged: true).count).to eq(staged_user_count)
    end
  end

  shared_examples "cleans up staged users" do |email_name, expected_exception|
    it "cleans up staged users" do
      staged_user_count = User.where(staged: true).count
      expect { process(email_name) }.to raise_error(expected_exception)
      expect(User.where(staged: true).count).to eq(staged_user_count)
    end
  end

  context "when email address is screened" do
    before { ScreenedEmail.expects(:should_block?).with("screened@mail.com").returns(true) }

    include_examples "does not create staged users",
                     :screened_email,
                     Email::Receiver::ScreenedEmailError
  end

  context "when the mail is auto generated" do
    include_examples "does not create staged users",
                     :auto_generated_header,
                     Email::Receiver::AutoGeneratedEmailError
  end

  context "when email is a bounced email" do
    include_examples "does not create staged users",
                     :bounced_email,
                     Email::Receiver::BouncedEmailError
  end

  context "when the body is blank" do
    include_examples "does not create staged users", :no_body, Email::Receiver::NoBodyDetectedError
  end

  context "when unsubscribe via email is not allowed" do
    include_examples "does not create staged users",
                     :unsubscribe_new_user,
                     Email::Receiver::UnsubscribeNotAllowed
  end

  context "when From email address is not on allowlist" do
    before do
      SiteSetting.allowed_email_domains = "example.com|bar.com"
      Fabricate(:group, incoming_email: "some_group@bar.com")
    end

    include_examples "does not create staged users",
                     :blocklist_allowlist_email,
                     Email::Receiver::EmailNotAllowed
  end

  context "when From email address is on blocklist" do
    before do
      SiteSetting.blocked_email_domains = "email.com|mail.com"
      Fabricate(:group, incoming_email: "some_group@bar.com")
    end

    include_examples "does not create staged users",
                     :blocklist_allowlist_email,
                     Email::Receiver::EmailNotAllowed
  end

  context "with blocklist and allowlist for To and Cc" do
    before { Fabricate(:group, incoming_email: "some_group@bar.com") }

    it "does not create staged users for email addresses not on allowlist" do
      SiteSetting.allowed_email_domains = "mail.com|example.com"
      process(:blocklist_allowlist_email)

      expect(User.find_by_email("alice@foo.com")).to be_nil
      expect(User.find_by_email("bob@foo.com")).to be_nil
      expect(User.find_by_email("carol@example.com")).to be_present
    end

    it "does not create staged users for email addresses on blocklist" do
      SiteSetting.blocked_email_domains = "email.com|foo.com"
      process(:blocklist_allowlist_email)

      expect(User.find_by_email("alice@foo.com")).to be_nil
      expect(User.find_by_email("bob@foo.com")).to be_nil
      expect(User.find_by_email("carol@example.com")).to be_present
    end
  end

  context "when destinations aren't matching any of the incoming emails" do
    include_examples "does not create staged users",
                     :bad_destinations,
                     Email::Receiver::BadDestinationAddress
  end

  context "when email is sent to category" do
    context "when email is sent by a new user and category does not allow strangers" do
      fab!(:category) do
        Fabricate(:category, email_in: "category@foo.com", email_in_allow_strangers: false)
      end

      include_examples "does not create staged users",
                       :new_user,
                       Email::Receiver::StrangersNotAllowedError
    end

    context "when email has no date" do
      fab!(:category) do
        Fabricate(:category, email_in: "category@foo.com", email_in_allow_strangers: true)
      end

      it "includes the translated string in the error" do
        expect { process(:no_date) }.to raise_error(Email::Receiver::InvalidPost).with_message(
          I18n.t("system_messages.email_reject_invalid_post_specified.date_invalid"),
        )
      end

      include_examples "does not create staged users", :no_date, Email::Receiver::InvalidPost
    end

    context "with forwarded emails behaviour set to quote" do
      before { SiteSetting.forwarded_emails_behaviour = "quote" }

      context "with a category which allows strangers" do
        fab!(:category) do
          Fabricate(:category, email_in: "team@bar.com", email_in_allow_strangers: true)
        end
        include_examples "creates topic with forwarded message as quote", :category, "team@bar.com"
      end

      context "with a category which doesn't allow strangers" do
        fab!(:category) do
          Fabricate(:category, email_in: "team@bar.com", email_in_allow_strangers: false)
        end
        include_examples "cleans up staged users",
                         :forwarded_email_1,
                         Email::Receiver::StrangersNotAllowedError
      end
    end
  end

  context "when email is a reply" do
    before do
      configure_reply_by_email
      Fabricate(:post_reply_key, reply_key: reply_key, user: user, post: post)
    end

    let(:reply_key) { "4f97315cc828096c9cb34c6f1a0d6fe8" }

    fab!(:category)
    fab!(:user) { Fabricate(:user, email: "discourse@bar.com", refresh_auto_groups: true) }
    fab!(:user2) { Fabricate(:user, email: "someone_else@bar.com") }
    fab!(:topic) { create_topic(category: category, user: user) }
    fab!(:post) { create_post(topic: topic, user: user) }

    context "when the email address isn't matching the one we sent the notification to" do
      include_examples "does not create staged users",
                       :reply_user_not_matching,
                       Email::Receiver::ReplyUserNotMatchingError
    end

    context "with forwarded emails behaviour set to create replies" do
      before { SiteSetting.forwarded_emails_behaviour = "create_replies" }

      context "when a reply contains a forwarded email" do
        include_examples "does not create staged users", :reply_and_forwarded
      end

      context "with forwarded email to category that doesn't allow strangers" do
        before { category.update!(email_in: "team@bar.com", email_in_allow_strangers: false) }

        include_examples "cleans up staged users",
                         :forwarded_email_1,
                         Email::Receiver::StrangersNotAllowedError
      end
    end
  end

  context "when replying without key is allowed" do
    fab!(:group) { Fabricate(:group, incoming_email: "team@bar.com") }
    let!(:topic) do
      configure_reply_by_email
      SiteSetting.find_related_post_with_key = false
      process(:email_reply_1)
      Topic.last
    end

    context "when the topic was deleted" do
      before { topic.update_columns(deleted_at: 1.day.ago) }

      include_examples "cleans up staged users",
                       :email_reply_staged,
                       Email::Receiver::TopicNotFoundError
    end

    context "when the topic was closed" do
      before { topic.update_columns(closed: true) }

      include_examples "cleans up staged users",
                       :email_reply_staged,
                       Email::Receiver::TopicClosedError
    end

    context "when they aren't allowed to like a post" do
      before { topic.update_columns(archived: true) }

      include_examples "cleans up staged users",
                       :email_reply_like,
                       Email::Receiver::InvalidPostAction
    end
  end

  it "does not remove the incoming email record when staged users are deleted" do
    expect { process(:bad_destinations) }.to change { IncomingEmail.count }.and raise_error(
            Email::Receiver::BadDestinationAddress,
          )
    expect(IncomingEmail.last.message_id).to eq("9@foo.bar.mail")
  end
end
