#!/usr/bin/env ruby
# frozen_string_literal: true

socket_path, owner_pid, gemfile_path = ARGV

discourse_root = File.expand_path("..", __dir__)
ENV["BUNDLE_GEMFILE"] = gemfile_path || File.join(discourse_root, "Gemfile")

require "rubygems"
require "bundler/setup"

$LOAD_PATH.unshift(File.join(discourse_root, "lib"))
require "discourse_vips/broker"

Process.setproctitle("discourse discourse_vips")
DiscourseVips::Broker.new(socket_path:, owner_pid: Integer(owner_pid)).run
