#!/bin/bash

# This script lists all bundled plugins in the Discourse project.
# It accepts an optional suffix argument that will be appended to each plugin name.
#
# Usage:
#   ./list_bundled_plugins [suffix]
#
# Arguments:
#   suffix: An optional string to append to each plugin name.
#

set -e -u -o pipefail

suffix=${1:-}
git ls-tree --name-only -d HEAD plugins/* | sed "s|$|$suffix|"
