<DModal
  class="custom-date-range-modal"
  @title={{i18n "admin.dashboard.reports.dates"}}
  @closeModal={{@closeModal}}
>
  <:body>
    <DateTimeInputRange
      @from={{this.startDate}}
      @to={{this.endDate}}
      @onChange={{this.onChangeDateRange}}
      @showFromTime={{false}}
      @showToTime={{false}}
    />
  </:body>
  <:footer>
    <DButton
      @action={{this.updateDateRange}}
      @label="admin.dashboard.reports.refresh_report"
      @icon="arrows-rotate"
    />
  </:footer>
</DModal>