<DModal
  @headerClass="hidden"
  class="dismiss-notification-confirmation"
  @closeModal={{@closeModal}}
>
  <:body>
    {{@model.confirmationMessage}}
  </:body>
  <:footer>
    <DButton
      @icon="check"
      class="btn-primary"
      @action={{this.dismiss}}
      @label="notifications.dismiss_confirmation.dismiss"
    />
    <DButton
      @action={{@closeModal}}
      @label="notifications.dismiss_confirmation.cancel"
      class="btn-default"
    />
  </:footer>
</DModal>