/*
 This file is auto-generated from the Discourse core database schema. Instead of editing it directly,
 please update the `schema.yml` configuration file and re-run the `generate_schema` script to update it.
*/

CREATE TABLE users (
  id INTEGER NOT NULL PRIMARY KEY,
  username TEXT NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  name TEXT,
  seen_notification_id INTEGER NOT NULL,
  last_posted_at DATETIME,
  password_hash TEXT,
  salt TEXT,
  active BOOLEAN NOT NULL,
  username_lower TEXT NOT NULL,
  last_seen_at DATETIME,
  admin BOOLEAN NOT NULL,
  last_emailed_at DATETIME,
  trust_level INTEGER NOT NULL,
  approved BOOLEAN NOT NULL,
  approved_by_id INTEGER,
  approved_at DATETIME,
  previous_visit_at DATETIME,
  suspended_at DATETIME,
  suspended_till DATETIME,
  date_of_birth DATE,
  views INTEGER NOT NULL,
  flag_level INTEGER NOT NULL,
  ip_address TEXT,
  moderator BOOLEAN,
  title TEXT,
  uploaded_avatar_id INTEGER,
  locale TEXT,
  primary_group_id INTEGER,
  registration_ip_address TEXT,
  staged BOOLEAN NOT NULL,
  first_seen_at DATETIME,
  silenced_till DATETIME,
  group_locked_trust_level INTEGER,
  manual_locked_trust_level INTEGER,
  secure_identifier TEXT,
  flair_group_id INTEGER,
  last_seen_reviewable_id INTEGER,
  password_algorithm TEXT
);