{{yield
  (hash
    data=this.data
    uploading=this.uploading
    uploadProgress=this.uploadProgress
    uploaded=this.uploaded
    submitDisabled=this.submitDisabled
    startUpload=this.startUpload
  )
  this.uppyUpload.setup
}}