<MenuPanel
  @animationClass={{this.animationClass}}
  @panelClass="search-menu-panel"
>
  <SearchMenu
    @onClose={{@closeSearchMenu}}
    @inlineResults={{true}}
    @autofocusInput={{true}}
  />
</MenuPanel>