intermediate_db: /shared/import/intermediate.db
mappings_db: /shared/import/mappings.db
uploads_db: /shared/import/uploads.db

config:
  # if false, allows reserved usernames only for admins
  always_allow_reserved_usernames: true
