<ListSetting
  @value={{this.settingValue}}
  @choices={{this.groupChoices}}
  @settingName="name"
  @mandatoryValues={{this.setting.mandatory_values}}
  @nameProperty={{this.nameProperty}}
  @valueProperty={{this.valueProperty}}
  @onChange={{this.onChangeGroupListSetting}}
/>