name: Publish @discourse/types package

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - "0-a-types-again"
    paths:
      - "lib/version.rb"

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    if: github.repository == 'discourse/discourse'
    container: discourse/discourse_test:slim
    timeout-minutes: 5

    steps:
      - name: Set working directory owner
        run: chown root:root .

      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: Generate external type definitions
        run: pnpm types:generate

      - name: Generate type definitions
        run: pnpm lint:types

      - name: Prepare version
        shell: bash
        run: |
          discourse_version=$(ruby -r ./lib/version.rb -e 'puts "#{Discourse::VERSION::MAJOR}.#{Discourse::VERSION::MINOR}.#{Discourse::VERSION::TINY}"')
          commit_hash=$(git rev-parse --short HEAD)
          package_version="${discourse_version}-${commit_hash}"

          echo "@discourse/types version: ${package_version}"
          sed -i -E  "s/\"version\": \"0\.0\.0\"/\"version\": \"${package_version}\"/" frontend/discourse-types/package.json

      - name: Publish the package
        working-directory: frontend/discourse-types
        run: pnpm publish --no-git-checks --dry-run
