name: Release - prepare release bump

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The release branch to prepare the next version for, e.g. `release/2015.11`"
        required: true
        type: string
  push:
    branches:
      - release/*

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: run
    runs-on: ubuntu-latest
    container: discourse/discourse_test:slim
    timeout-minutes: 10

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Install gh cli
        run: |
          # https://github.com/cli/cli/blob/trunk/docs/install_linux.md#debian-ubuntu-linux-raspberry-pi-os-apt
          (type -p wget >/dev/null || (sudo apt update && sudo apt install wget -y)) \
            && sudo mkdir -p -m 755 /etc/apt/keyrings \
            && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
            && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
            && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
            && sudo mkdir -p -m 755 /etc/apt/sources.list.d \
            && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
            && sudo apt update \
            && sudo apt install gh -y

      - name: Set working directory owner
        run: chown root:root .

      - uses: actions/checkout@v5
        with:
          filter: tree:0
          fetch-depth: 0

      - name: Bundler cache
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gem-

      - name: Setup gems
        run: |
          bundle config --local path vendor/bundle
          bundle config --local deployment true
          bundle config --local without development
          bundle install --jobs 4
          bundle clean

      - name: Create a PR for the next version bump
        run: bin/rake "release:prepare_next_version_branch[${{ inputs.branch || github.ref_name }}]"
