name: Tests

on:
  pull_request:
  push:
    branches:
      - main
      - beta
      - stable
      - release/*

permissions:
  contents: read

jobs:
  build:
    name: plugins frontend
    runs-on: ubuntu-latest
    container: discourse/discourse_test:release
    timeout-minutes: 60

    defaults:
      run:
        shell: bash

    env:
      RAILS_ENV: test
      PGUSER: discourse
      PGPASSWORD: discourse
      LOAD_PLUGINS: 1
      CHEAP_SOURCE_MAPS: "1"
      EMBER_ENV: development
      QUNIT_REUSE_BUILD: 1

    steps:
      - name: Set working directory owner
        run: chown root:root .

      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup Git
        run: |
          git config --global user.email "ci@ci.invalid"
          git config --global user.name "Discourse CI"

      - name: Start redis
        run: redis-server /etc/redis/redis.conf &

      - name: Start Postgres
        run: |
          chown -R postgres /var/run/postgresql
          sudo -E -u postgres script/start_test_db.rb
          sudo -u postgres psql -c "CREATE ROLE $PGUSER LOGIN SUPERUSER PASSWORD '$PGPASSWORD';"

      - name: Symlink vendor/bundle from image
        run: ln -s /var/www/discourse/vendor/bundle vendor/bundle

      - name: Setup gems
        run: |
          bundle config --local path vendor/bundle
          bundle config --local deployment true
          bundle config --local without development
          bundle install --jobs $(($(nproc) - 1))
          bundle clean

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: Checkout official plugins
        run: bin/rake plugin:install_all_official

      - name: Symlink plugin gems from image
        run: |
          for dir in /var/www/discourse/plugins/*/gems; do
            plugin_name=$(basename "$(dirname "$dir")")
            plugin_dir="plugins/$plugin_name"
            gem_dir="$plugin_dir/gems"
            if [ ! -d "$plugin_dir" ]; then
              echo "Skipping $plugin_name: Plugin directory does not exist"
            elif [ -d "$gem_dir" ]; then
              echo "Skipping $plugin_name: Source gems directory exists"
            else
              echo "Symlinking $dir to $gem_dir"
              ln -s "$dir" "$gem_dir"
            fi
          done

      - name: Set QUNIT_PARALLEL
        run: echo "QUNIT_PARALLEL=$(($(nproc) / 2))" >> $GITHUB_ENV

      - name: Create and migrate database
        run: |
          bin/rake db:create
          script/silence_successful_output bin/rake db:migrate

      - name: Ember Build
        run: script/assemble_ember_build.rb

      - name: Plugins QUnit
        run: bin/rake 'plugin:qunit[*]'
